name: Android CD - Firebase Deploy

on:
  workflow_run:
    workflows: ["Android CI - Continuous Integration"]  # ⚠️ Use o nome EXATO do seu CI!
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from CI
        uses: actions/download-artifact@v4
        with:
          name: app-debug-apk
          
      - name: List downloaded files
        run: ls -la  # Para debug
          
      - name: Deploy to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: 'testers'
          file: app-debug-apk/app-debug.apk  # ⚠️ Caminho correto!
          debug: true